import { Link } from 'react-router-dom'
import { ArrowRight, CalendarDays, Building2, Bell, Users, Compass, Activity, MapPin, Clock, Sparkles } from 'lucide-react'
import Navbar from '../../components/layout/Navbar'
import Footer from '../../components/layout/Footer'
import Button from '../../components/common/Button'
import Badge from '../../components/common/Badge'
import { useApi } from '../../hooks/useApi'
import EventCard from '../../components/events/EventCard'
import ClubCard from '../../components/clubs/ClubCard'
import NoticeCard from '../../components/notices/NoticeCard'

function fmt(d){if(!d)return '';return new Date(d).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
function day(d){if(!d)return '';return new Date(d).getDate()}
function month(d){if(!d)return '';return new Date(d).toLocaleDateString('en-US',{month:'short'})}

const features=[
 [CalendarDays,'Discover events','Find workshops, competitions, seminars, cultural programs, and campus activities.'],[Building2,'Explore clubs','Discover university clubs that match your interests and ambitions.'],[Bell,'Stay updated','Never miss an important university notice or announcement.'],[Users,'Connect','Join communities and participate in life beyond the classroom.'],[Activity,'Manage activities','Keep your events, registrations, and club activity organized.'],[Compass,'One campus','Bring students, organizations, and administration together.']
]
export default function Landing(){const {data:eventsRaw}=useApi('/events',{params:{limit:3}});const {data:clubsRaw}=useApi('/clubs',{params:{limit:3}});const {data:noticesRaw}=useApi('/notices',{params:{limit:3}});const events=(eventsRaw||[]).map(e=>({...e,id:e._id,date:fmt(e.date),day:day(e.date),month:month(e.date),registrations:e.registrationCount||0,time:e.startTime}));const clubs=(clubsRaw||[]).map(c=>({...c,id:c._id,members:c.memberCount||0}));const notices=(noticesRaw||[]).map(n=>({...n,id:n._id,date:fmt(n.publishedAt||n.createdAt)}));return <div className="public-page"><Navbar/><main>
 <section className="hero"><div className="hero-orb"/><div className="container hero-grid"><div className="hero-copy"><div className="signal-badge"><i/>Built for university life</div><h1>Your campus.<br/><span>One connected hub.</span></h1><p>Discover events, connect with clubs, stay updated, and experience university life in one beautifully organized platform.</p><div className="hero-actions"><Link to="/events"><Button>Explore campus <ArrowRight size={18}/></Button></Link><Link to="/register"><Button variant="secondary">Get started</Button></Link></div><div className="hero-trust"><span><b>{events.length>0?'2,400+':'—'}</b> students connected</span><span><b>{clubs.length||'—'}</b> active organizations</span></div></div><DashboardPreview clubs={clubs} events={events}/></div></section>
 <section className="section feature-section"><div className="container"><div className="section-heading"><p className="eyebrow">The campus, composed</p><h2>Everything your campus needs.<br/><span>In one place.</span></h2><p>Less time searching. More time discovering, participating, and belonging.</p></div><div className="feature-grid">{features.map(([Icon,title,text],i)=><article key={title} className="feature-card"><span className="feature-number">0{i+1}</span><Icon size={24}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="section"><div className="container"><SectionTop eyebrow="Around campus" title="Worth showing up for." copy="Fresh opportunities to learn, meet people, and make something memorable." to="/events" label="View all events"/><div className="card-grid event-grid">{events.slice(0,3).map(e=><EventCard event={e} base="/events" key={e.id}/>)}</div></div></section>
 <section className="section split-tone"><div className="container"><SectionTop eyebrow="Find your people" title="Communities with momentum." copy="Explore student-led organizations built around shared interests and real work." to="/clubs" label="Explore clubs"/><div className="card-grid">{clubs.slice(0,3).map(c=><ClubCard club={c} base="/clubs" key={c.id}/>)}</div></div></section>
 <section className="section"><div className="container notice-preview"><div><div className="section-heading left"><p className="eyebrow">Notice board</p><h2>Stay in the loop.</h2><p>Important campus information, clearly prioritized and easy to find.</p><Link to="/notices"><Button variant="secondary">Browse all notices</Button></Link></div></div><div className="notice-list">{notices.slice(0,3).map(n=><NoticeCard notice={n} key={n.id}/>)}</div></div></section>
 <section className="cta-section"><div className="container cta-card"><div><p className="eyebrow">A better-connected campus</p><h2>Your university life,<br/>beautifully organized.</h2></div><Link to="/register"><Button>Join CampusHub <ArrowRight size={18}/></Button></Link></div></section>
 </main><Footer/></div>}

function SectionTop({eyebrow,title,copy,to,label}){return <div className="section-top"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{copy}</p></div><Link to={to}>{label}<ArrowRight size={17}/></Link></div>}
function DashboardPreview({clubs=[],events=[]}){return <div className="preview-wrap"><div className="preview-glow"/><div className="dashboard-preview"><header><div><span/><span/><span/></div><small>STUDENT OVERVIEW</small><Sparkles size={16}/></header><div className="preview-body"><aside><b>CH</b>{[1,2,3,4,5].map(i=><i key={i} className={i===1?'active':''}/>)}</aside><section><div className="preview-welcome"><div><small>GOOD MORNING</small><h3>Campus at a glance.</h3></div><Badge tone="amber">{new Date().toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'})}</Badge></div><div className="preview-stats"><div><CalendarDays/><span>Upcoming</span><b>{String(events.length).padStart(2,'0')}</b></div><div><Building2/><span>Clubs</span><b>{String(clubs.length).padStart(2,'0')}</b></div><div><Bell/><span>Unread</span><b>—</b></div></div><div className="preview-panels"><div className="preview-event"><div className="preview-label">NEXT EVENT <span>View all</span></div><h4>{events[0]?.title||'No events yet'}</h4><p><Clock/> {events[0]?`${events[0].date} · ${events[0].time}`:'—'}</p><p><MapPin/> {events[0]?.location||'—'}</p><div className="preview-attendees"><span/><span/><span/><small>+{events[0]?.registrations||0} going</small></div></div><div className="preview-activity"><div className="preview-label">CLUB ACTIVITY</div>{clubs.slice(0,3).map(c=><div key={c.id}><i style={{background:c.accent||'#F59E0B'}}/><span>{c.initials}<small>{c.category}</small></span><b>↗</b></div>)}</div></div></section></div></div></div>}
